### ISSUE TITLE
Raw as the default viewing mode 

### ISSUE THREAD

**Issue by soren11** [SergiX44/XBackBone#291]
Is it possible for one to have raw images as the default viewing mode? 

For example I’d have website.com/—-/——.png which would show the raw version, I prefer to use raw but in my opinion having /raw at the end of the link looks somewhat messy.

**Comment by SergiX44** [comment]
But doesn't that defeat one of the main purposes of the software? For this you lose an audio and video player, buttons to copy the url/download the file, document previews, etc.
From what is given this necessity?
If you need this kind of bare minimum is not better to use a script like https://github.com/Xenthys/ShareXen ?

Please do not take it as an attack, I am just curious because it is not the first request I have of this kind

**Comment by soren11** [comment]
xbackbone is nice due to the user management, on sharexen you don't have the ability to clear a users account like you do on xbackbone.

**Comment by Lisalhol** [comment]
> But doesn't that defeat one of the main purposes of the software? For this you lose an audio and video player, buttons to copy the url/download the file, document previews, etc.
> From what is given this necessity?
> If you need this kind of bare minimum is not better to use a script like https://github.com/Xenthys/ShareXen ?
> 
> Please do not take it as an attack, I am just curious because it is not the first request I have of this kind

I would also like this. Usually, the audio/video player is already implemented with majority browsers (chrome/firefox)
Isn't the purpose determined by the user? A toggle to make .png the raw option? 
IMGUR has it /imagelink for the media player/copyurl and have the /imagelink.png as the image itself. Something like this could be a compromise? Not telling you how to do your job, just putting my input as a end user! Thank you for all your work so far!

**Comment by BaxAndrei** [comment]
I personally do not agree, I like exactly how it is now. I think a solution would be to add an option in the settings to choose the default display mode, so everyone can choose what they want.
