### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by yuvali1337** [SergiX44/XBackBone#36]
What does orphaned files mean?
Is there a way to let site guests upload a photo without any logins?
How can i let users who are not admins to change the gallery view? (I tried removing the if *admin but it didnt work quite well)

Sorry im really shit at coding just trying to figure out some things :)

**Comment by SergiX44** [comment]
> What does orphaned files mean?

When an account is deleted, all the uploaded files from that account are not deleted but still stored and available (if published in origin), keeped as "orphaned files". If you want to remove these file, you can purge them from the system settings.

> Is there a way to let site guests upload a photo without any logins?

Currently no, all uploaded files are associated with the uploader account.

> How can i let users who are not admins to change the gallery view?

Users now can only use the gallery mode, the table mode is available for admin just because the number of media per page is higher with more options.

**Comment by yuvali1337** [comment]
Thanks for the quick answer, I would love to have these features in the near future.
