### ISSUE TITLE
Defalut link is not raw

### ISSUE THREAD

**Issue by guzlewski** [SergiX44/XBackBone#51]
Hello, i'd like to have raw in defalut link. I use php 7.2 with phpfileinfo and nginx.
Using link in img tag (https://sharex.geniush.ovh/6e4bd/5d407cab554cd.png) or discord not load image, but  https://sharex.geniush.ovh/6e4bd/5d407cab554cd.png/raw works.

Similar to https://github.com/SergiX44/XBackBone/issues/14 but no solution.

**Comment by SergiX44** [comment]
In the custom uploader settings, just add "/raw" to the URL field.
But, if the image tag (non-raw url) is contacted by discord it should download it automatically, because if XBackBone is getting a request from a crawler/robot (like google, etc, inclunding discord) should return the raw image.
Is Discord returning a error or something?

![raw](https://user-images.githubusercontent.com/4172890/62306160-967bfe00-b481-11e9-8462-2a5714c2ea80.png)

**Comment by guzlewski** [comment]
Discord wasn't showing image becouse I had cloudflare hotlink protection enabled. I disabled it and its working good. Only in github markdown image tag url needs /raw
