### ISSUE TITLE
Transfer existing XBackBone instance to another host

### ISSUE THREAD

**Issue by derMiepz** [sergix44/XBackBone#574]
Heya!
my current webhost is shutting down their service so I'm forced to switch to another one. Now I'm wondering if there's a way to move my current XBackBone instance to another host without loosing any files and without breaking any existing links. The domain has already been transferred to the new host.

Thanks in advance for you help!

**Comment by driverspy** [comment]
Hey, I've done that from time to time too.
I have the simplest settings in xBackBone.

As stupid as it sounds, you have to download all (really all) files for the xBackBone and upload them to the new host.
For example, via `FileZilla` or `WinSCP` (i.e. via FTP).

Then you can open the xBackBone on the new host.
If you get the status code 500, you may have to check whether the paths are correct in the `config.php`.
The paths for the `sqlite` (if used) and the `storage` folder must be specified correctly there.

Only then will you be able to log in again as usual :)

At least that's how I've always done it. So far it's worked fine for me.

If you're not sure about the paths, you need to write to the administrator so that he can give you the information.

But I also think that `__dir__` could work.

**Comment by derMiepz** [comment]
Heya, thanks for your reply!
I already managed to get it working late at night and forgot close this issue 😅
It was indeed `config.php` that I forgot to check for the sqlite DB path.

Maybe this issue will help others fixing the Error 500 😄
