### ISSUE TITLE
Customization of app name 

### ISSUE THREAD

**Issue by DirtyCajunRice** [SergiX44/XBackBone#63]
**Describe the solution you'd like**
Ability to change the app name in config.php without having to change the app name in bootstrap folder
**Additional context**
This does not get rid of the link on the bottom, this solely is to change the login page/title/header from XBackBone to custom

**Comment by SergiX44** [comment]
You shouldn't edit the boostrap file, things can go very wrong.
The ability to change the app name is already implemented: https://github.com/SergiX44/XBackBone#change-app-install-name

The footer cannot be changed, because since this is a free software under agpl license, and those would be the credits and license under which the software is distributed (as well as a way to let other people know about the project)
